### ISSUE TITLE
Forward forward in tensorflow

### ISSUE THREAD

**Issue by aliaa80** [mohammadpz/pytorch_forward_forward#2]
Hi, I want forward forward in tensorflow. Hass anyone implemented this algorithm with tensorflow?

**Comment by amirrezarajabi** [comment]
Hello my dear friend

You can use our [repo](https://github.com/amirrezarajabi/Tensorflow-Forward-Forward) 
I hope it helps you

**Comment by aliaa80** [comment]
Thanks a lot
It worked.
