### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by mohamed82008** [mohammadpz/pytorch_forward_forward#3]
Thanks for this repo. This repo has no license file. So legally, I don't think anyone can download, use, reproduce, modify or redistribute it in its current form.

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by abdelwahed** [comment]
I have the same concern

**Comment by mohammadpz** [comment]
Thanks! I just added an MIT license.
